name: Deploy autodoc to Github Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: github.repository_owner == 'zigtools'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: zig build docs --summary all

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "zig-out/doc/lsp-codegen"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
