name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: [master]
        os: [ubuntu-latest, macos-latest]
        include:
          - zig-version: "0.12.0"
            os: ubuntu-latest
          - zig-version: "0.13.0"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - run: zig env

      - run: zig fmt --ast-check --check src

      - name: zig build
        run: zig build install test --summary all
