name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        zig-version: [master]
        os: [ubuntu-latest, macos-latest]
        include:
          - zig-version: "0.12.0"
            os: ubuntu-latest
          - zig-version: "0.13.0"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - run: zig env

      - name: zig build test
        run: |
          wget https://raw.githubusercontent.com/microsoft/vscode-languageserver-node/main/protocol/metaModel.json
          zig build install test --summary all

      - run: zig fmt --ast-check --check zig-out/artifacts/lsp.zig

      - name: Upload artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: zig-out/artifacts/*
